Axis17/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from axis.views import not_found
from django.conf.urls import handler404

urlpatterns = [
    url(r'^axis-admin/', admin.site.urls),
    url(r'^', include('axis.urls', namespace="axis")),
    url(r'^bakerstreet/', include('bakerstreet.urls', namespace="bakerstreet")),
    url(r'^turboflux/', include('turboflux.urls', namespace="turboflux")),
    url(r'^freakomatix/', include('freakomatix.urls', namespace="freakomatix")),
    url(r'^electroblitz/', include('electroblitz.urls', namespace="electroblitz")),
    url(r'^api-auth/', include('rest_framework.urls')),
    # url('', include('social_django.urls', namespace='social'))
    # url(r'^select2/', include('select2.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# urlpatterns += [
#     url(r'^[a-zA-Z]+', not_found),
# ]
#
handler404 = not_found

axis/urls.py
from django.conf.urls import url, include
from django.contrib import admin
# from django.contrib.sitemaps.views import sitemap
# from axis.sitemaps import *

from . import views

app_name = 'axis'

# Dictionary containing your sitemap classes
# sitemaps = {
#    'static': StaticSitemap,
# }

urlpatterns = [

    url(r'^$', views.home, name='home'),
    url(r'^team/$', views.team, name='team'),
    url(r'^tns/$', views.tns, name='tns'),
    url(r'^tshirt/$', views.tshirt, name='tshirt'),
    url(r'^inauguration/$', views.inauguration, name='inauguration'),
    url(r'^techie-nite/$', views.techie_nite, name='techie_nite'),
    # url(r'^tyou/$', views.tyou, name='tyou'),
    # url(r'^bakerstreet/$', views.bakerstreet, name='bakerstreet'),
    # url(r'^bakerstreet_rules/$', views.bakerstreet_rules, name='bakerstreet_rules'),
    url(r'^logout/$', views.log_out, name='logout'),
    url(r'^about/$', views.about, name='about'),
    url(r'^event_categories/$', views.event_categories, name='event_categories'),
    # url(r'^event_categories/(?P<size>[0-9]+)/$', views.set_size_redirect, name='set_size_redirect'),
    url(r'^event_categories/$', views.event_categories, name='event_categories'),
    # url(r'^event_categories/(?P<slug>[\w-]+)/$', views.events, name='events'),
    url(r'^register_for_event/(?P<event_id>[0-9]+)/$', views.register_for_event, name='register_for_event'),
    url(r'^create_team/(?P<event_id>[0-9]+)/$', views.create_team, name='create_team'),
    url(r'^workshops/$', views.workshops, name='workshops'),
    url(r'^validate_email/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', views.validate_email, name="validate_email"),
    # url(r'^googletokensignin', views.google_signin, name="googletokensignin"),
    url(r'^updates/$', views.updates, name='updates'),
    url(r'^sponsors/$', views.sponsors, name='sponsors'),
    url(r'^attractions/$', views.attractions, name='attractions'),
    url(r'^guestlectures/$', views.guestlectures, name='guestlectures'),
    url(r'^talks/$', views.talks, name='talks'),
    url(r'^social_initiatives/$', views.initiatives, name='social_initiatives'),
    url(r'^exhibition/$', views.exhibitions, name='exhibition'),
    url(r'^googleb1165711f14fb6e5.html/$', views.google_site_verification, name='google_site_verification'),
    url(r'^sitemap/$', views.sitemap, name='sitemap'),
    url(r'^api/', include('axis.api_urls', namespace="api_urls")),
    # url(r'^api/events$', views.event_list, name='api_event_list'),
    # url(r'^api/workshops$', views.workshops_list, name='api_workshops_list'),
    # url(r'^api/guest_lectures$', views.guest_lectures_list, name='api_guest_lectures_list'),
    # url(r'^api/social_initiatives$', views.social_initiatives_list, name='api_social_initiatives_list'),
    # url(r'^api/exhibitions$', views.exhibitions_list, name='api_exhibitions_list'),
    # url(r'^api/talks$', views.talks_list, name='api_talks_list'),
    # url(r'^api/timeline$', views.timeline_list, name='api_timeline_list'),
    # url(r'^api/current_updates$', views.current_updates_list, name='api_current_updates_list'),
    # url(r'^api/event_categories$', views.event_category_list, name='api_event_category_list'),
    # url(r'^api/login$', views.api_login, name='api_login'),
    # url(r'^events/(?P<cat_slug>[\w-]+)/(?P<event_slug>[\w-]+)/$', views.event, name='event'),
    # url(r'^requests/$', views.requests, name='requests'),
    # url(r'^requests/accept/(?P<team_id>[0-9]+)/$', views.accept_request, name='accept_request'),
    # url(r'^requests/reject/(?P<req_id>[0-9]+)/$', views.reject_request, name='reject_request'),
    # url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps},
    #     name='django.contrib.sitemaps.views.sitemap'),
]

axis/forms.py
from django import forms


class EmailForm(forms.Form):
    body = forms.CharField(
        max_length=5000,
        required=False,
        widget=forms.Textarea,
    )

    subject = forms.CharField(
        max_length=100,
        required=True,
        help_text='Enter a subject for the email?',
    )
    # email_body_template = 'email/account/withdraw.txt'

    field_order = (
        'subject',
        'body',
    )

axis/views.py
from django.contrib.auth.tokens import default_token_generator
from django.contrib import messages
from django.shortcuts import render, redirect, get_object_or_404
from django.template import loader
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.views.decorators.csrf import csrf_exempt
from rest_framework.utils import json

from axis.admin import UserCreationForm, UserChangeForm
from django.contrib.auth import authenticate, login, logout, get_user_model
from django.http import HttpResponse
from .models import MyUser, Event, EventCategory, Team, Request, CurrentUpdates, SingleParticipantEventRegistration, \
    TimeLine, GuestLectures, GuestLectureQuestions, Workshop, SocialInitiative, Exhibition, Talks, Schedule, \
    Inauguration, Summit, InaugurationQuestions, TechieNite

from datetime import datetime
from django.core.exceptions import ObjectDoesNotExist
from django.core.mail import send_mail
from Axis17.settings import EMAIL_HOST_USER
from rest_framework import status
from rest_framework.decorators import api_view, authentication_classes, permission_classes
from rest_framework.authentication import SessionAuthentication, BasicAuthentication
from rest_framework.permissions import IsAuthenticated
from rest_framework.response import Response
from .serializers import EventSerializer, EventCategorySerializer, MyUserLoginSerializer, \
    WorkshopSerializer, GuestLecturesSerializer, SocialInitiativeSerializer, ExhibitionSerializer, TalksSerializer, \
    TimeLineSerializer, CurrentUpdatesSerializer, UserCreationSerializer, \
    SingleEventRegistration, TeamEventRegistration, WorkshopRegistrationSerializer, ScheduleSerializer, \
    InaugurationSerializer, SummitSerializer, TechieNiteSerializer


def about(request):
    if request.method == 'POST' and ('password' in request.POST or 'password1' in request.POST):
        return login_signup(request, 'axis/about.html')
    else:
        return render(request, 'axis/about.html', {'user_registrations': UserRegistration(request.user)})


def team(request):
    if request.method == 'POST' and ('password' in request.POST or 'password1' in request.POST):
        return login_signup(request, 'axis:team')
    else:
        return render(request, 'axis/team.html',
                      {'user_registrations': UserRegistration(request.user)})

def tns(request):
    Summits = Summit.objects.all().order_by('id')
    if request.method == 'POST' and ('Login' in request.POST or 'Signup' in request.POST):
        return login_signup(request, 'axis:tns', {'Summits': Summits})

    elif request.method == 'POST' and ('register' in request.POST):
        for summit in Summits:
            summit.user.add(request.user)
            summit.save()
        messages.success(request, "Successfully registered for TNS!")
        return redirect('axis:tns')
    # elif request.method == 'POST' and ('submit_question' in request.POST) and (request.POST['question'] != ''):
    #     text = request.POST['question']
    #     inaug_question = InaugurationQuestions()
    #     inaug_question.user = request.user
    #     inaug_question.text = text
    #     inaug_question.save()
    #     messages.info(request, "Question Submitted!")
    #     return redirect('axis:inauguration')
    else:
        is_registered = False
        is_closed = False
        if request.user.is_authenticated:
            user = request.user
            for summit in Summits:
                if summit.registrations_closed:
                    is_closed = True
                if summit in user.summit_set.all():
                    is_registered = True

        return render(request, 'axis/tns.html',
                      {'Summits': Summits,
                       'is_registered': is_registered, 'is_closed': is_closed})


# pata nahi kisne kiya ye
#
#
# def login_signups(request, page, context={}):
#     request.session['message'] = ""
#     request.session['message_type'] = ""
#     if 'Login' in request.POST:
#         email = request.POST['email']
#         password = request.POST['password']
#         flag = True
#         # u = get_object_or_404(MyUser, email=email)
#         try:
#             u = MyUser.objects.get(email=email)
#         except ObjectDoesNotExist:
#             request.session['message'] = "Invalid Credentials"
#             request.session['message_type'] = "error"
#             __context = {"message_type": request.session['message_type'],
#                          "message": request.session['message'],
#                          }
#             __context.update(context)
#             return render(request, page, __context)
#
#         '''
#         if u is None:
#             request.session['message'] = "Invalid Credentials"
#             request.session['message_type'] = "error"
#             __context = {"message_type": request.session['message_type'],
#                                                       "message": request.session['message'],
#                                                     }
#             __context.update(context)
#             return render(request, page, __context)
#         '''
#         if not u.is_active:
#             print(u.f_name)
#             flag = False
#             u.is_active = True
#             u.save()
#
#         user = authenticate(email=email, password=password)
#         # print(user.l_name)
#         if not flag:
#             # u = MyUser.objects.get(email=email)
#             print(user.axis_id)
#             user.is_active = False
#             user.save()
#             flag = True
#         # print(user.f_name)
#         if user is not None:
#             if user.is_active:
#                 # print("active")
#                 login(request, user)
#                 request.session['message'] = "You've been successfully logged in!"
#                 request.session['message_type'] = "success"
#                 __context = {
#                     "message_type": request.session['message_type'],
#                     "message": request.session['message'],
#                     "remove_hash": "remove_hash",
#                     'increase_delay': "increase_delay"
#                 }
#                 __context.update(context)
#                 return render(request, page, __context)
#             else:
#                 # print("not active!!!!!!")
#                 request.session['message'] = "Please validate your account first!"
#                 request.session['message_type'] = "error"
#                 __context = {
#                     "message_type": request.session['message_type'],
#                     "message": request.session['message'],
#                     "remove_hash": "remove_hash",
#                     "increase_delay": "increase_delay",
#                 }
#                 __context.update(context)
#                 return render(request, page, __context)
#
#         else:
#             # print("hahaha")
#             request.session['message'] = "Invalid Credentials"
#             request.session['message_type'] = "error"
#             __context = {
#                 "message_type": request.session['message_type'],
#                 "message": request.session['message'],
#                 "increase_delay": "increase_delay",
#             }
#             __context.update(context)
#             return render(request, page, __context)
#
#     elif "Signup" in request.POST:
#         form = UserCreationForm(request.POST or None)
#         if form.is_valid():
#             user = form.save(commit=False)
#             email = form.cleaned_data['email']
#             password = form.cleaned_data['password1']
#             user.set_password(password)
#             user.date_created = datetime.now()
#             user.is_active = False
#             user.is_admin = False
#             user.save()
#             user.axis_id = 'AXIS18' + (str(user.pk + 4235).zfill(5))
#             user.save()
#             # print(user.axis_id)
#             link = request.META['HTTP_HOST']
#             send_validation_email(user, link, password)
#             request.session['message'] = "Successfully Registered! Please check your mail to validate your account!!"
#             request.session['message_type'] = "success"
#             __context = {
#                 "message_type": request.session['message_type'],
#                 "message": request.session['message'],
#                 "remove_hash": "remove_hash",
#                 "increase_delay": "increase_delay",
#             }
#             __context.update(context)
#             return render(request, page, __context)
#
#         else:
#             request.session['message'] = "Email Id already exists! Please try signing up using different email" \
#                                          " address."
#             request.session['message_type'] = "error"
#             __context = {
#                 "message_type": request.session['message_type'],
#                 "message": request.session['message'],
#                 "increase_delay": "increase_delay",
#             }
#             __context.update(context)
#             return render(request, page, __context)
#
#
# def homes(request):
#     request.session['message'] = ""
#     request.session['message_type'] = ""
#     if request.method == 'POST' and ('Login' in request.POST or 'Signup' in request.POST):
#         return login_signup(request, "axis/home.html")
#     else:
#         current_updates = CurrentUpdates.objects.all()
#
#         return render(request, 'axis/home.html',
#                       {
#                           'user_registrations': UserRegistration(request.user),
#                           "message_type": request.session['message_type'],
#                           "message": request.session['message'],
#                           "current_updates": current_updates
#                       })
#


def log_out(request):

axis/templates/axis/attractions.html
{% extends 'axis/base.html' %}
{%  load static %}

{% block title %}
    <title>Attractions | AXIS'18</title>
    <meta name="keywords" content="Axis,Attractions,Techfest,VNIT, VNIT Techfest,NIT Nagpur Techfest,Nagpur Techfest,Central India Techfest,Central India Biggest Techfest,etc">
    <meta name="description" content="AXIS is the largest technical festival of Central India.">

{% endblock %}

    {% block stylesheetsAndScriptsInHead %}
    <link rel="stylesheet" type="text/css" href="{% static 'axis/css/attractions.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'axis/css/sponsors.css' %}" />
    <link href="https://fonts.googleapis.com/css?family=Roboto:300" rel="stylesheet">
    <script src="{% static 'axis/js/modernizr.custom.js' %}"></script>



{% endblock %}

{% block content %}

    <div class="container attractions-container">
    <div class="row heading-attractions">
        <br />
        <h1>
            ATTRACTIONS
        </h1>
        <hr class="attractions-line"/>

        <div class="col-xs-10 col-xs-offset-1">
            <div class = "attractions-paper ">
                <h2>INAUGURATION</h2>
                <hr class="attractions-line sponsor-grid"/>
                <div class="container title-sponsor-grid" >
                    <div class="row-eq-height">
                        <div class="col-sm-5  title-s " >
                            <img id="igniting" src="{% static 'axis/images/inaug.jpg' %}" class="img-responsive center-block title-spons" style="height: 70%"/>
                        </div>
                    </div>
                    <div class="col-sm-5" style="padding: 8%">
                        <div class="box">
                            <a href="{% url 'axis:inauguration' %}" style="">Know More...</a>
{#                            cursor: default; pointer-events: none;#}
                        </div>
                    </div>
                    <br/>
                </div>
            </div>
        </div>

        <div class="col-xs-10 col-xs-offset-1">
            <div class = "attractions-paper ">
                <h2>TNS</h2>
                <hr class="attractions-line sponsor-grid"/>
                <div class="container title-sponsor-grid" >
                    <div class="row-eq-height">
                        <div class="col-sm-5  title-s " >
                            <img id="igniting" src="{% static 'axis/images/tns_website.jpg' %}" class="img-responsive center-block title-spons" style="height: 70%"/>
                        </div>
                    </div>
                    <div class="col-sm-5" style="padding: 8%">
                        <div class="box">
                            <a href="{% url 'axis:tns' %}">Know More...</a>

                        </div>
                    </div>
                    <br/>
                </div>
            </div>
        </div>


        <div class="col-xs-10 col-xs-offset-1">
            <div class = "attractions-paper ">
                <h2>IGNITING MINDS</h2>
                <hr class="attractions-line sponsor-grid"/>
                <div class="container title-sponsor-grid" >
                    <div class="row-eq-height">
                        <div class="col-sm-5  title-s " >
                            <img id="igniting" src="../../static/axis/images/igniting_minds.jpg" class="img-responsive center-block title-spons" style="height: 70%"/>
                        </div>
                    </div>
                    <div class="col-sm-5" style="padding: 5%">
                        <div class="box">
                            <a href="{% url 'axis:guestlectures' %}">GUEST LECTURES</a>
                            <hr class="attractions-line"/>
                            <a href="{% url 'axis:talks' %}" style="">TALKS</a>
                        </div>
                    </div>
                    <br/>
                </div>
            </div>
        </div>

        <div class="col-xs-10 col-xs-offset-1">
            <div class = "attractions-paper ">
                <h2>EXHIBITIONS</h2>
                <hr class="attractions-line sponsor-grid"/>
                <div class="container title-sponsor-grid" >
                    <div class="row-eq-height">
                        <div class="col-sm-5  title-s " >
                            <img id="igniting" src="../../static/axis/images/exhibition.jpg" class="img-responsive center-block title-spons" style="height: 70%"/>
                        </div>
                    </div>
                    <div class="col-sm-5" style="padding: 8%">
                        <div class="box">
{#                            <a href="#" style="cursor: default; pointer-events: none;">EXHIBITIONS</a>#}
                            <!-- After release of Exhibitions page use the a tag below-->
                            <a href="{% url 'axis:exhibition' %}">ISRO</a>

                        </div>
                    </div>
                    <br/>
                </div>
            </div>
        </div>

        <div class="col-xs-10 col-xs-offset-1">
            <div class = "attractions-paper ">
                <h2>TECHIE NITE</h2>
                <hr class="attractions-line sponsor-grid"/>
                <div class="container title-sponsor-grid" >
                    <div class="row-eq-height">
                        <div class="col-sm-5  title-s " >
                            <img id="igniting" src="../../static/axis/images/TECHIE.jpg" class="img-responsive center-block title-spons" style="height: 70%"/>
                        </div>
                    </div>
                    <div class="col-sm-5" style="padding: 8%">
                        <div class="box">
{#                            <a href="#" style="cursor: default; pointer-events: none;">EXHIBITIONS</a>#}
                            <!-- After release of Exhibitions page use the a tag below-->
                            <a href="{% url 'axis:techie_nite' %}">Know More...</a>

                        </div>
                    </div>
                    <br/>
                </div>
            </div>
        </div>

    </div>

{#    <div class="col-xs-10 col-xs-offset-1">#}
{#        <div class = "attractions-paper ">#}
{#            <h2>INAUGURATION</h2>#}
{#            <hr class="attractions-line sponsor-grid"/>#}
{#            <div class="container title-sponsor-grid" >#}
{#                <div class="row">#}
{#                    <div class="col-sm-5 vcenter title-s" >#}
{#                    <img id="igniting123" src="../../static/axis/images/coming_soon2.png" class="img-responsive center-block title-spons" style="height: 70%"/>#}
{#                    </div>#}
{#                    <div class="col-sm-5 vcenter outer-box" >#}
{#                        <br />#}
{#                        <div class="box" style="font-size: 158%;">#}
{#                            STAY TUNED#}
{#                        </div>#}
{#                    </div>#}
{#                    <br />#}
{#                </div>#}
{#		    </div>#}
{#        </div>#}
{#    </div>#}



{#    <div class="col-xs-10 col-xs-offset-1">#}
{#        <div class = "attractions-paper ">#}
{#            <h2>Exhibitions</h2>#}
{#            <hr class="attractions-line sponsor-grid"/>#}
{#            <div class="container title-sponsor-grid" >#}
{#                <div class="row">#}
{#                    <div class="col-sm-5 vcenter title-s" >#}
{#                    <img id="igniting123" src="../../static/axis/images/coming_soon2.png" class="img-responsive center-block title-spons" style="height: 70%"/>#}
{#                    </div>#}
{#                     <div class="col-sm-5" style="padding: 5%">#}
{#                         <div class="box">#}
{#                             <a href="{% url 'axis:exhibition' %}" style="font-size: 188%;"></a>#}
{#                         </div>#}
{#                    </div>#}
{#                    <br />#}
{#                </div>#}
{#		    </div>#}
{#        </div>#}
{#    </div>#}

{##}
{#        <div class="col-xs-10 col-xs-offset-1">#}
{#        <div class = "attractions-paper ">#}
{#            <h2>Exhibitions</h2>#}
{#            <hr class="attractions-line sponsor-grid"/>#}
{#            <div class="container title-sponsor-grid" >#}
{#                <div class="row-eq-height">#}
{#                    <div class="col-sm-5  title-s " >#}
{##}
{#                                <img id="igniting" src="../../static/axis/images/coming_soon2.png" class="img-responsive center-block title-spons" style="height: 70%"/>#}
{##}
{#                        </div>#}
{#                    </div>#}
{#                    <div class="col-sm-5" style="padding: 5%">#}
{##}
{#                                    <div class="box">#}
{#                                    <span href="{% url 'axis:exhibition' %}" style="font-size: 188%;">Exhibition</span>#}
{##}
{##}
{#                                    </div>#}
{#                    </div>#}
{#                    <br/>#}
{#                </div>#}
{#		    </div>#}
{#        </div>#}

{#        <div class="col-xs-10 col-xs-offset-1">#}
{#        <div class = "attractions-paper ">#}
{#            <h2>Exhibitions</h2>#}
{#            <hr class="attractions-line sponsor-grid"/>#}
{#            <div class="container title-sponsor-grid" >#}
{#                <div class="row-eq-height">#}
{#                    <div class="col-sm-5  title-s " >#}
{##}
{#                                <img id="igniting" src="../../static/axis/images/igniting_minds.jpg" class="img-responsive center-block title-spons" style="height: 70%"/>#}
{##}
{#                        </div>#}
{#                    </div>#}
{#                    <div class="col-sm-5" style="padding: 5%">#}
{##}
{#                                    <div class="box">#}
{#                                    <a href="{% url 'axis:exhibition' %}" style="font-size: 188%;">Exhibition</a>#}
{##}
{##}
{#                                    </div>#}
{#                    </div>#}
{#                    <br/>#}
{#                </div>#}
{#		    </div>#}
{#        </div>#}

    </div>

{#    </div>#}
{#    </div>#}


{% endblock %}

axis/templates/axis/email.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link href="https://fonts.googleapis.com/css?family=Roboto:100,300" rel="stylesheet">
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <title>Email-Validation</title>
    <style>
        p, h2, a{
            text-align: center;
        }
        .main {
            border-radius: 8px;
            min-width: 80%;
        }
        p, a {
            font-size: 14px;
        }
        @media screen and (min-width: 480px){
            .main {
                width: 80%;
            }
        }
    </style>
</head>
<body>
    <div style="background: #e4e4e4; height: auto; margin: 0 auto; padding: 20px;" class="main">
        <h2 style="color: #515151">Verify your email, {{ name }}!</h2>
        <div style="background-color: #ffffff; margin: 20px auto; padding: 20px; font-family: Roboto,serif" class="main">
            <p>
                Please note your AXIS'18 ID: <b>{{ axis_id }}</b>. This ID will be used for all further communication.
            </p>
            <p>Your registration details are:</p>
            <p><b>Email-ID: </b>{{ email }}</p>
            <p><b>Password: </b>{{ password }}</p>
            <p> Please verify your email id by clicking on the link below...</p>
            <div style="text-align: center">
                <a href="{{ link }}">
                    {{ link }}
                </a>
            </div>
            <p style="font-size: 12px">
                Facing any difficulty in login? Contact us at <b>+91-8983973404</b>.
            </p>
        </div>
    </div>
</body>
</html>

axis/templates/axis/filter.html
<!DOCTYPE html>
<html lang="en">
<head>
    <script
  src="https://code.jquery.com/jquery-3.2.1.min.js"
  integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
  crossorigin="anonymous"></script>
    <script>
        // console.log(id_token);
{#        var xhr = new XMLHttpRequest();#}
{#        xhr.open('POST', 'http://localhost:8000/event_categories/');#}
{#        xhr.withCredentials = false;#}
{#        xhr.setRequestHeader('Content-Type', 'application/x-www-form-urlencoded');#}
{#        xhr.onload = function() {#}
{##}
{#        };#}
{#        w = xhr.send('width=' + screen.width);#}
{#        console.log(w);#}
{#        window.location = "{% url 'axis:event_categories' %}" + "?width=" + screen.width.toString();#}
{#        alert('kaha tak aaya');#}
        $(document).ready(
            function () {
{#                alert('haaha');#}
                var a = document.getElementById('width');
                a.value = screen.width;
{#                alert(a.value);#}
                $('#sub').trigger('click');
            }
        )
    </script>
</head>
<body>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <label>
            <input type="number" name="width" id="width" style="display: none" />
            <input type="submit" id="sub" style="display: none" />
        </label>
    </form>
</body>
</html>

axis/templates/axis/googleb1165711f14fb6e5.html
google-site-verification: googleb1165711f14fb6e5.html

axis/templates/axis/login.html
<!DOCTYPE html>
<html lang="en">
<head>

</head>
<body>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <label for="email">Email</label>
        <input type="email" id="email" name="email" />
        <label for="pw">Password</label>
        <input type="password" id="pw" name="password" />
        <input type="submit" value="Log In" />
    </form>
</body>
</html>