Axis17/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from axis.views import not_found
from django.conf.urls import handler404

urlpatterns = [
    url(r'^axis-admin/', admin.site.urls),
    url(r'^', include('axis.urls', namespace="axis")),
    url(r'^bakerstreet/', include('bakerstreet.urls', namespace="bakerstreet")),
    url(r'^turboflux/', include('turboflux.urls', namespace="turboflux")),
    url(r'^freakomatix/', include('freakomatix.urls', namespace="freakomatix")),
    url(r'^electroblitz/', include('electroblitz.urls', namespace="electroblitz")),
    url(r'^api-auth/', include('rest_framework.urls')),
    # url('', include('social_django.urls', namespace='social'))
    # url(r'^select2/', include('select2.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# urlpatterns += [
#     url(r'^[a-zA-Z]+', not_found),
# ]
#
handler404 = not_found

axis/urls.py
from django.conf.urls import url, include
from django.contrib import admin
# from django.contrib.sitemaps.views import sitemap
# from axis.sitemaps import *

from . import views

app_name = 'axis'

# Dictionary containing your sitemap classes
# sitemaps = {
#    'static': StaticSitemap,
# }

urlpatterns = [

    url(r'^$', views.home, name='home'),
    url(r'^team/$', views.team, name='team'),
    url(r'^tns/$', views.tns, name='tns'),
    url(r'^tshirt/$', views.tshirt, name='tshirt'),
    url(r'^inauguration/$', views.inauguration, name='inauguration'),
    url(r'^techie-nite/$', views.techie_nite, name='techie_nite'),
    # url(r'^tyou/$', views.tyou, name='tyou'),
    # url(r'^bakerstreet/$', views.bakerstreet, name='bakerstreet'),
    # url(r'^bakerstreet_rules/$', views.bakerstreet_rules, name='bakerstreet_rules'),
    url(r'^logout/$', views.log_out, name='logout'),
    url(r'^about/$', views.about, name='about'),
    url(r'^event_categories/$', views.event_categories, name='event_categories'),
    # url(r'^event_categories/(?P<size>[0-9]+)/$', views.set_size_redirect, name='set_size_redirect'),
    url(r'^event_categories/$', views.event_categories, name='event_categories'),
    # url(r'^event_categories/(?P<slug>[\w-]+)/$', views.events, name='events'),
    url(r'^register_for_event/(?P<event_id>[0-9]+)/$', views.register_for_event, name='register_for_event'),
    url(r'^create_team/(?P<event_id>[0-9]+)/$', views.create_team, name='create_team'),
    url(r'^workshops/$', views.workshops, name='workshops'),
    url(r'^validate_email/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', views.validate_email, name="validate_email"),
    # url(r'^googletokensignin', views.google_signin, name="googletokensignin"),
    url(r'^updates/$', views.updates, name='updates'),
    url(r'^sponsors/$', views.sponsors, name='sponsors'),
    url(r'^attractions/$', views.attractions, name='attractions'),
    url(r'^guestlectures/$', views.guestlectures, name='guestlectures'),
    url(r'^talks/$', views.talks, name='talks'),
    url(r'^social_initiatives/$', views.initiatives, name='social_initiatives'),
    url(r'^exhibition/$', views.exhibitions, name='exhibition'),
    url(r'^googleb1165711f14fb6e5.html/$', views.google_site_verification, name='google_site_verification'),
    url(r'^sitemap/$', views.sitemap, name='sitemap'),
    url(r'^api/', include('axis.api_urls', namespace="api_urls")),
    # url(r'^api/events$', views.event_list, name='api_event_list'),
    # url(r'^api/workshops$', views.workshops_list, name='api_workshops_list'),
    # url(r'^api/guest_lectures$', views.guest_lectures_list, name='api_guest_lectures_list'),
    # url(r'^api/social_initiatives$', views.social_initiatives_list, name='api_social_initiatives_list'),
    # url(r'^api/exhibitions$', views.exhibitions_list, name='api_exhibitions_list'),
    # url(r'^api/talks$', views.talks_list, name='api_talks_list'),
    # url(r'^api/timeline$', views.timeline_list, name='api_timeline_list'),
    # url(r'^api/current_updates$', views.current_updates_list, name='api_current_updates_list'),
    # url(r'^api/event_categories$', views.event_category_list, name='api_event_category_list'),
    # url(r'^api/login$', views.api_login, name='api_login'),
    # url(r'^events/(?P<cat_slug>[\w-]+)/(?P<event_slug>[\w-]+)/$', views.event, name='event'),
    # url(r'^requests/$', views.requests, name='requests'),
    # url(r'^requests/accept/(?P<team_id>[0-9]+)/$', views.accept_request, name='accept_request'),
    # url(r'^requests/reject/(?P<req_id>[0-9]+)/$', views.reject_request, name='reject_request'),
    # url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps},
    #     name='django.contrib.sitemaps.views.sitemap'),
]

turboflux/urls.py
from django.conf.urls import url, include
from django.contrib import admin
# from django.contrib.sitemaps.views import sitemap
# from axis.sitemaps import *

from . import views

app_name = 'turboflux'

urlpatterns = [

    url(r'^$', views.home, name='home'),
    url(r'^rules/$', views.rules, name='rules'),
    # url(r'^test-completed/$', views.test_completed, name='test_completed'),
    # url(r'^ajax-leaderboard/$', views.ajax_leaderboard, name='ajax_leaderboard'),
    url(r'^test-over/$', views.time_completed, name='time_completed')

]

turboflux/models.py
from django.db import models
from axis.models import MyUser


class Test(models.Model):
    name = models.CharField(max_length=50, null=False, default="Round")
    start = models.DateTimeField()
    end = models.DateTimeField()
    conduct_this_test = models.BooleanField(default=True)
    duration = models.DurationField()

    def __str__(self):
        return str(self.name)


class Question(models.Model):
    A = 'A'
    B = 'B'
    C = 'C'
    D = 'D'

    ANSWER_CHOICE = (
        (A, 'A'),
        (B, 'B'),
        (C, 'C'),
        (D, 'D'),
    )

    test = models.ForeignKey(Test, null=False, on_delete=models.CASCADE)
    image = models.FileField(null=True, upload_to="turboflux_test_images/", blank=True)
    text = models.TextField(max_length=5000, null=False, blank=True)
    answer = models.CharField(max_length=2, null=False, choices=ANSWER_CHOICE, default=A)
    marks = models.FloatField(null=False, default=0)
    negative_marks = models.FloatField(null=False, default=0)

    def __str__(self):
        return str(self.id) + ": " + self.text


class TurbofluxUserTestMetadata(models.Model):
    questions_answered = models.ManyToManyField(Question, blank=True)
    user = models.ForeignKey(MyUser, null=False, on_delete=models.CASCADE)
    test = models.ForeignKey(Test, null=False, on_delete=models.CASCADE)
    score = models.FloatField(default=0)
    last_question_id = models.IntegerField(null=True, blank=True)
    started_at = models.DateTimeField(auto_now_add=True)

    def update_answer(self, question_id: int, answer):
        question = Question.objects.get(id=question_id)

        try:
            self.questions_answered.get(id=question_id)
            return
        except Question.DoesNotExist:
            self.questions_answered.add(question)

        if question.answer == answer:
            self.score += question.marks
        else:
            self.score -= question.negative_marks

        self.save()

    def __str__(self):
        return "Round " + str(self.test.name) + " : " + str(self.user.f_name) + " - " + str(self.questions_answered)

    def save(self, force_insert=False, force_update=False, using=None, update_fields=None, last_question_id=None):
        if last_question_id is None:
            self.last_question_id = self.test.question_set.all().order_by('id')[0].id
        else:
            q = Question.objects.get(id=last_question_id)
            if q.test == self.test:
                self.last_question_id = last_question_id

        super().save()

turboflux/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, HttpResponse
from axis.views import event_registration_email
from axis.models import MyUser, Event, SingleParticipantEventRegistration
from axis.views import login_signup
from .models import TurbofluxUserTestMetadata, Test, Question
from django.contrib import messages
import json
import datetime
from django.utils import timezone


def rules(request):
    if request.method == 'GET':
        return render(request, 'turboflux/turboflux_rules.html')
    elif request.method == 'POST' and ('password' in request.POST or 'password1' in request.POST):
        return login_signup(request, "turboflux:home")
    elif request.method == 'POST' and 'PLAY' in request.POST:
        # register_for_bakerstreet(request)
        return redirect('turboflux:home')


# @login_required(login_url='/#login')
def home(request):
    if request.user.is_anonymous:
        return redirect('turboflux:rules')

    try:
        test = Test.objects.get(start__lte=timezone.now(), end__gte=datetime.datetime.now())
    except Test.DoesNotExist:
        return redirect('turboflux:time_completed')

    if request.method == 'POST':
        user_metadata = TurbofluxUserTestMetadata.objects.get(test=test, user=request.user)

        if 'submit_answer' in request.POST:
            question_id = request.POST['question_id']
            answer = str(request.POST['answer']).upper()
            user_metadata.update_answer(question_id, answer)
            messages.info(request, "Answer submitted.")
        elif 'change_question' in request.POST:
            user_metadata.save(last_question_id=int(request.POST['question_id']))

        return redirect('turboflux:home')

    try:
        user_metadata = TurbofluxUserTestMetadata.objects.get(user=request.user, test=test)
    except TurbofluxUserTestMetadata.DoesNotExist:
        if (test.end - timezone.now()).total_seconds() < test.duration.total_seconds():
            return redirect('turboflux:time_completed')
        user_metadata = TurbofluxUserTestMetadata.objects.create(test=test, user=request.user)
        user_metadata.save()

    questions = user_metadata.test.question_set.all().order_by('id')
    last_question = Question.objects.get(id=user_metadata.last_question_id)

    attempted_question_ids = []

    for q in user_metadata.questions_answered.all().only('id'):
        attempted_question_ids.append(q.id)

    if (test.end - user_metadata.started_at) > test.duration:
        countdown = test.duration.total_seconds() - (timezone.now() - user_metadata.started_at).total_seconds()
    else:
        countdown = (test.end - timezone.now()).seconds

    if countdown <= 0:
        return redirect('turboflux:time_completed')

    return render(request, 'turboflux/home.html', context={
        'questions': questions,
        'countdown': countdown,
        'last_question': last_question,
        'attempted_question_ids': attempted_question_ids
    })


def time_completed(request):
    try:
        test = Test.objects.get(start__lte=datetime.datetime.now(), end__gte=datetime.datetime.now())

        if (test.end - timezone.now()).total_seconds() < test.duration.total_seconds():
            raise Test.DoesNotExist

        try:
            metadata = TurbofluxUserTestMetadata.objects.get(user=request.user, test=test)
            if (timezone.now() - metadata.started_at).total_seconds() > test.duration.total_seconds():
                raise Test.DoesNotExist
        except Test.DoesNotExist:
            raise Test.DoesNotExist

        return redirect('turboflux:home')
    except Test.DoesNotExist:
        try:
            test = Test.objects.order_by('start').get(start__gt=datetime.datetime.now())
            return render(request, 'turboflux/time_completed.html', context={'test': test})
        except Test.DoesNotExist:
            return render(request, 'turboflux/time_completed.html', context={})

turboflux/templates/turboflux/Thank_you.html
{% extends 'axis/base.html' %}

{%  load static %}

{% block title %}
    <title>Thank_You | AXIS'18</title>
    <meta name="keywords" content="Axis,T-shirt Axis,T-shirt Techfest VNIT, VNIT Techfest,NIT Nagpur Techfest T-shirt,Nagpur Techfest T-shirt,Central India Techfest,Central India Biggest Techfest,etc">
    <meta name="description" content="Axis is the biggest technical festival of Central India.">

{% endblock %}

{% block stylesheetsAndScriptsInHead %}
    <link rel="stylesheet" type="text/css" href="{% static 'axis/css/updates.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'axis/css/bakerstreet.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Satisfy" rel="stylesheet" type="text/css">
    <style>

         #bakerstreet_rules_page
         {
             background: url({% static 'axis/images/event_backgrounds/221b-baker-street.jpeg'%}) ;
             position:relative;top:0;height: 100%;width: 100%;

         }


        @media screen and (max-width: 800px) {

            #bakerstreet_rules_page
             {
                overflow-x: hidden;
                 position:absolute;top:0;
                 height:100%;
                 background: url({% static 'axis/images/event_backgrounds/221b-baker-street.jpeg' %});
             }
            #mobile
            {margin-top: 20%;margin-bottom: 10%;}


        }



    </style>

{% endblock %}

{% block content %}

<div  id="bakerstreet_rules_page" style="">
   <div id="" style="width: 100%;height: 100%;">
&nbsp;
        <div class="container" style="margin-top: 5%">

            <div class="jumbotron" style="background-color: rgba(0,0,0,0.5);color: white">
                <h1>Congratulations !!!</h1>
                <p>You have successfully completed the test! Thank You for participating!</p>
             </div>
            <div id="leaderboard">

                    </div>

        </div>

       <div class="row">&nbsp;</div>
       <div class="row">&nbsp;</div>
       <div class="row">&nbsp;</div>
       <div class="row">&nbsp;</div>
       <div class="row">&nbsp;</div>
       <div class="row">&nbsp;</div><div class="row">&nbsp;</div><div class="row">&nbsp;</div>



<div class="row">&nbsp;</div>

   </div>
</div>
    <script>
        $(document).ready(function () {
            function get_leaderboard() {

{#                alert("in setInterval");#}
                var row = $('#leaderboard');
                $.ajax({
                    url: "/bakerstreet/ajax-leaderboard/",
                    type: "post",
                    dataType: 'json' // ** ensure you add this line **

                }).success(function (data) {

                    var s = ("<table class=\"table\" style=\"background-color: rgba(0,0,0,0.3); color: whitesmoke; text-align: center;\">" +
                        "<tr style=\"color: black; background-color: white\">" +
                            "<td>Rank</td>" +
                            "<td>Name</td>" +
                            "<td>Score</td>" +
                        "</tr>");

                    var counter = 0;

                    jQuery.each(data.leaderboard, function (index, item) {
                        counter++;

                        if(counter != data.leaderboard.length) {
                            s += ("<tr>" + "<td>" + counter + "</td>" +
                                "<td>" + data.leaderboard[index].user__f_name + " " + data.leaderboard[index].user__l_name + "</td>" +
                                "<td>" + data.leaderboard[index].questions_solved + " " +
                                "</tr>");
                        }
                        else{
                            s += ("<tr style=\"color: black; background-color: white\">" + "<td>" + data.my_rank + "</td>" +
                                "<td>" + data.leaderboard[index].user__f_name + " " + data.leaderboard[index].user__l_name + "</td>" +
                                "<td>" + data.leaderboard[index].questions_solved + " " +
                                "</tr>");
                        }
                    });

                    s += ("</table>");
                    row.html(s);

                })

            }
            get_leaderboard();
            setInterval(get_leaderboard, 10000);
    {#    setInterval(function(){ alert("Hello"); }, 3000);#}
        })
    </script>

{% endblock %}

turboflux/templates/turboflux/rules.html
{% extends 'axis/base.html' %}

{%  load static %}

{% block title %}
    <title>Exam Rules | AXIS'18</title>
    <meta name="keywords" content="221B Bakerstreet London, 221B, Bakerstreet Rules, Axis, Techfest VNIT, VNIT Techfest,NIT Nagpur Techfest,Nagpur Techfest,Central India Techfest,Central India Biggest Techfest,etc">
    <meta name="description" content="Axis is the biggest technical festival of Central India.">

{% endblock %}

{% block stylesheetsAndScriptsInHead %}
		<link rel="stylesheet" type="text/css" href="{% static 'bakerstreet/css/rules.css' %}" />
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-xs-12">
                <h2>Rules</h2>
                <p>Rules will be here</p>

                {% if request.user.is_anonymous %}
                    <button type="button" disabled="disabled">Please Login to Play !!</button>
                {% else %}
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <button type="submit" name="PLAY">Click here to Play !!</button>
                    </form>
                {% endif %}
            </div>

        </div>
    </div>
{% endblock %}

turboflux/templates/turboflux/test_completed.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <p>Show leader board here and also thank you for participating message!</p>
</body>
</html>

turboflux/templates/turboflux/time_completed.html
{% extends 'axis/base.html' %}

{%  load static %}

{% block title %}
    <title>Time's Over! | AXIS'18</title>
    <meta name="keywords" content="Axis,T-shirt Axis,T-shirt Techfest VNIT, VNIT Techfest,NIT Nagpur Techfest T-shirt,Nagpur Techfest T-shirt,Central India Techfest,Central India Biggest Techfest,etc">
    <meta name="description" content="Axis is the biggest technical festival of Central India.">

{% endblock %}

{% block stylesheetsAndScriptsInHead %}
    <link rel="stylesheet" type="text/css" href="{% static 'axis/css/updates.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'axis/css/bakerstreet.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Satisfy" rel="stylesheet" type="text/css">
    <style>

         #bakerstreet_rules_page
         {
             background: url({% static 'axis/images/event_backgrounds/221b-baker-street.jpeg'%}) ;
             position:relative;top:0;height: 100%;width: 100%;

         }


        @media screen and (max-width: 800px) {

            #bakerstreet_rules_page
             {
                overflow-x: hidden;
                 position:absolute;top:0;
                 height:100%;
                 background: url({% static 'axis/images/event_backgrounds/221b-baker-street.jpeg' %});
             }
            #mobile
            {margin-top: 20%;margin-bottom: 10%;}


        }



    </style>

{% endblock %}

{% block content %}

<div  id="bakerstreet_rules_page" style="">
   <div id="" style="width: 100%;height: 100%;">
&nbsp;
        <div class="container" style="margin-top: 5%">

            <div class="jumbotron" style="background-color: rgba(0,0,0,0.5);color: white">
                <h1>Test Over!</h1>
                {% if test %}
                    <p>Don't worry another test is going to be held on {{ test.start }} IST</p>
                {% else %}
                    <p>All tests of Turboflux have been completed.</p>
                {% endif %}
             </div>
            <div id="leaderboard">

            </div>

        </div>

       <div class="row">&nbsp;</div>
       <div class="row">&nbsp;</div>
       <div class="row">&nbsp;</div>
       <div class="row">&nbsp;</div>
       <div class="row">&nbsp;</div>
       <div class="row">&nbsp;</div><div class="row">&nbsp;</div><div class="row">&nbsp;</div>


<div class="row">&nbsp;</div>

   </div>
</div>

{% endblock %}

turboflux/templates/turboflux/turboflux_rules.html
{% extends 'axis/base.html' %}

{%  load static %}

{% block title %}
    <title>Exam Rules | AXIS'18</title>
    <meta name="keywords" content="Axis,T-shirt Axis,T-shirt Techfest VNIT, VNIT Techfest,NIT Nagpur Techfest T-shirt,Nagpur Techfest T-shirt,Central India Techfest,Central India Biggest Techfest,etc">
    <meta name="description" content="Axis is the biggest technical festival of Central India.">

{% endblock %}

{% block stylesheetsAndScriptsInHead %}
    <link rel="stylesheet" type="text/css" href="{% static 'axis/css/updates.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'axis/css/bakerstreet.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Satisfy" rel="stylesheet" type="text/css">
    <style>

         #bakerstreet_rules_page
         {
             background: url({% static 'axis/images/event_backgrounds/turboflux.jpeg' %}) ;
             position:relative;top:0;height: 100vh;width: 100%;
             background-position: center;
             background-repeat: no-repeat;
             background-size: cover;
         }
          .table
        {
            color: #FFFFFF;
            font-family: 'nexa_boldregular', sans-serif;
        }
          #question
        {
            text-align: center;font-family: 'Satisfy' , cursive;    background-color: #222;
             border-color: #080808;color: #fff;font-size: 175%;margin-bottom: 0px;background-color: rgba(0,0,0,0);
             border: none;
        }
            #question123
        {
            text-align: center;font-family: 'Satisfy' , cursive;    background-color: #222;
             border-color: #080808;color: #fff;font-size: 175%;background-color: rgba(0,0,0,0);
             border: none;margin-bottom: 0px;
        }
        #nichekibtn
            {display:block;margin:0 auto;width: 200px;margin-top: 0.2%;margin-bottom: 2vh;}

        @media screen and (max-width: 800px) {

            #bakerstreet_rules_page
             {
                overflow-x: hidden;
                 position:absolute;top:0;
                 height:100%;
                 background: url({% static 'axis/images/event_backgrounds/221b-baker-street.jpeg' %});
             }
            #mobile
            {margin-top: 20%;margin-bottom: 10%;}
            #nichekibtn
            {display:block;margin:0 auto;width: 200px;margin-top: 5%;margin-bottom: 2%;}
           .table
           {margin-right: 0px;margin-left: 0px;}


        }

    .table>tbody>tr>th,.table>tbody>tr>td{

    border-top: 0px solid #ddd;

}
    .table
    {margin-bottom: 0px;font-size: 2.1vh;}

    </style>

{% endblock %}

{% block content %}

<div  id="bakerstreet_rules_page" style="">
   <div id="mobile" style="">
            <h1 style="text-align: center; font-family: Raleway, sans-serif; color: #c5c2b8;margin-bottom: 0px;margin-top: 0px;"><span style="font-size:7vh">Turboflux Online Test</span></h1>

        <div>
            <div class="row" >
                <div class="col-sm-offset-2 col-sm-8" style="color: #FFFFFF">

                    <div id="question" class="well" >General Mode</div>

                    <table class="table" style="background-color: rgba(0,0,0,0.5);">

                      <tbody>
                                <tr>
                                  <th scope="row">1</th>
                                  <td>Question 1 to 8 carries 1 mark each and -0.5 for wrong answers.</td>
                                </tr>
                              <tr>
                                  <th scope="row">2</th>
                                  <td>Question 9 to 12 carries 2 mark each and -1 for wrong answers.</td>
                                </tr>
                              <tr>
                                  <th scope="row">3</th>
                                  <td>Question 13 to 15 carries 3 mark each and -1 for wrong answers.</td>
                                </tr>
                              <tr>
                                  <th scope="row">5</th>
                                  <td>The duration of exam is 45 minutes</td>
                                </tr>
                              <tr>
                                  <th scope="row">6</th>
                                  <td>
                                      <button type="submit" role="link" class="btn btn-success"
                                                        name="change_question">Q 1</button>
                                      &nbsp;&nbsp;&nbsp;&nbsp;
                                      This means that you have submitted the answer for this question.
                                  </td>
                                </tr>
                              <tr>
                                  <th scope="row">7</th>
                                  <td>
                                      <button type="submit" role="link" class="btn btn-warning"
                                                        name="change_question">Q 2</button>
                                      &nbsp;&nbsp;&nbsp;&nbsp;
                                      This means that you have not attempted this question.
                                  </td>
                                </tr>
                              <tr>
                                  <th scope="row">8</th>
                                  <td>
                                      <button type="submit" role="link" class="btn btn-info"
                                                        name="change_question">Q 3</button>
                                      &nbsp;&nbsp;&nbsp;&nbsp;
                                      This means you are reading this question now.
                                  </td>
                                </tr>

                      </tbody>

                    </table>

{#                    <div id="question123" class="well" >Story Mode</div>#}
{##}
{##}
{#                     <table class="table" style="background-color: rgba(0,0,0,0.5)">#}
{##}
{#                      <tbody>#}
{#                        <tr>#}
{#                          <th scope="row">1</th>#}
{#                          <td>Game consists of around 15-20 questions.</td>#}
{#                        </tr>#}
{#                      <tr>#}
{#                          <th scope="row">2</th>#}
{#                          <td>The questions will be a part of a story whose description will be#}
{#given prior to each question.</td>#}
{#                        </tr>#}
{#                      <tr>#}
{#                          <th scope="row">3</th>#}
{#                          <td>Hints for each question will be provided on fb page as well as on#}
{#the question page - <a href="https://www.facebook.com/221BBakerStreetAXIS" target="_blank">https://www.facebook.com/221BBakerStreetAXIS</a></td>#}
{#                        </tr>#}
{#                      <tr>#}
{#                          <th scope="row">4</th>#}
{#                          <td>Answers for each question should be in lowercase characters#}
{#only, having no space in between in case of answer comprising of#}
{#two or more words.</td>#}
{#                        </tr>#}
{##}
{##}
{##}
{#                      </tbody>#}
{#                    </table>#}
                      </div>

            </div>
                </div>

       <h4 style="text-align: center; font-family: Raleway, sans-serif; color: #c5c2b8;margin-bottom: 2%;margin-top: 1%;"><b>NOTE:</b> In case of any disputes, the decision taken by the AXIS Executive Committee
would be final and binding for all.</h4>

            {% if request.user.is_anonymous %}
                    <button id="nichekibtn" type="button" class="btn btn-success" disabled="disabled">Please Login to Play!</button>
                {% else %}
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
{#                        <button type="submit" class="btn btn-success" name="PLAY">Click here to Play !!</button>#}
                        <button id="nichekibtn"  class="btn btn-success" type="submit" href="{% url 'bakerstreet:home' %}" name="PLAY">Start Contest!</button>
                    </form>
                {% endif %}

   <div class="row"></div>

          <div class="row"></div>

          <div class="row"></div>
   <div class="row"></div>
   <div class="row"></div>
   <div class="row"></div>
   <div class="row"></div>
{#            <a id="nichekibtn"  class="btn btn-success" type="button" href="{% url 'bakerstreet:home' %}" target="_blank">Start Contest!</a>#}
   </div>
</div>

{% endblock %}